### ISSUE TITLE
folder_id does not uniquely identify patients

### ISSUE THREAD

**Issue by ijustlovemath** [jvargh7/imt-dataproduct-parsers-R#7]
The `folder_id` represents the time of "export", ie when all the data was zipped up and sent to the "IMT Data Export" folder.

The session can be defined by the name of the logs themselves, eg "IMT_data_log_$date.csv", "IMT_ERROR_LOG_$date.log"

The two dates in each name should agree to within 5 seconds of each other. Since we're only running one session per day, you could match them up to the day or hour to create an equivalent of `folder_id`

I'd rename this to `session_id` to be a little less ambiguous as to the meaning.

Here's some example Python code which identifies and yields pairs of data logs (not quite the same as ones we're using, ie they use a different prefix, but the important bit is the logic):

```python
def paired_logs(dates=None, directory="Pump Qualification Logs"):

    def sorted_files(prefix):
        regex = prefix + "_data_[0-9-\_]+.csv"
        return sorted(regex_files(regex, directory))
    def slice_range(files):
        if dates is None:
            return files
        start, stop = dates
        return [filename for filename in files if start <= logpath_to_date(filename) <= stop]
    def helper(prefix):
        return slice_range(sorted_files(prefix))

    pump_logs = helper("pump")
    scale_logs = helper("scale")

    delta = datetime.timedelta(seconds=1)
    for p, s in zip(pump_logs, scale_logs):
        pdate = logpath_to_date(p)
        sdate = logpath_to_date(s)

        if -delta <= pdate - sdate <= delta:
            yield p, s
        else:
            print(f"[ERROR] unmatched logs: {p}, {s}")


```

**Comment by jvargh7** [comment]
I put the 'delta' as [15 minutes](https://github.com/jvargh7/imt-dataproduct-parsers-R/blob/main/functions/match_logs.R) for now since time difference between 'data_log' and 'ERROR_LOG' was 7 and 13 minutes.
